/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteImport } from './routes/org'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/org/index'
import { Route as OrgTeamsRouteImport } from './routes/org/teams'
import { Route as OrgProjectRouteImport } from './routes/org/project'
import { Route as OrgBillingRouteImport } from './routes/org/billing'
import { Route as OrgProjectIndexRouteImport } from './routes/org/project/index'
import { Route as OrgOrgSettingIndexRouteImport } from './routes/org/org-setting/index'
import { Route as OrgProjectSDKRouteImport } from './routes/org/project/SDK'
import { Route as OrgProjectEditorRouteImport } from './routes/org/project/Editor'
import { Route as OrgAnalyticsAnalyticsRouteImport } from './routes/org/analytics/Analytics'
import { Route as OrgProjectTeamTeamRouteImport } from './routes/org/project/team/Team'
import { Route as OrgProjectSettingsSettingsRouteImport } from './routes/org/project/settings/Settings'
import { Route as OrgProjectNarrativeAssetsVariablesRouteImport } from './routes/org/project/narrative-assets/Variables'
import { Route as OrgProjectNarrativeAssetsStoryNodesRouteImport } from './routes/org/project/narrative-assets/StoryNodes'
import { Route as OrgProjectNarrativeAssetsQuestRouteImport } from './routes/org/project/narrative-assets/Quest'
import { Route as OrgProjectNarrativeAssetsLocationsRouteImport } from './routes/org/project/narrative-assets/Locations'
import { Route as OrgProjectNarrativeAssetsItemsRouteImport } from './routes/org/project/narrative-assets/Items'
import { Route as OrgProjectNarrativeAssetsFactionsRouteImport } from './routes/org/project/narrative-assets/Factions'
import { Route as OrgProjectNarrativeAssetsDialogueRouteImport } from './routes/org/project/narrative-assets/Dialogue'
import { Route as OrgProjectNarrativeAssetsConditionsRouteImport } from './routes/org/project/narrative-assets/Conditions'
import { Route as OrgProjectNarrativeAssetsCharactersRouteImport } from './routes/org/project/narrative-assets/Characters'

const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgTeamsRoute = OrgTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => OrgRoute,
} as any)
const OrgProjectRoute = OrgProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => OrgRoute,
} as any)
const OrgBillingRoute = OrgBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgRoute,
} as any)
const OrgProjectIndexRoute = OrgProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgProjectRoute,
} as any)
const OrgOrgSettingIndexRoute = OrgOrgSettingIndexRouteImport.update({
  id: '/org-setting/',
  path: '/org-setting/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgProjectSDKRoute = OrgProjectSDKRouteImport.update({
  id: '/SDK',
  path: '/SDK',
  getParentRoute: () => OrgProjectRoute,
} as any)
const OrgProjectEditorRoute = OrgProjectEditorRouteImport.update({
  id: '/Editor',
  path: '/Editor',
  getParentRoute: () => OrgProjectRoute,
} as any)
const OrgAnalyticsAnalyticsRoute = OrgAnalyticsAnalyticsRouteImport.update({
  id: '/analytics/Analytics',
  path: '/analytics/Analytics',
  getParentRoute: () => OrgRoute,
} as any)
const OrgProjectTeamTeamRoute = OrgProjectTeamTeamRouteImport.update({
  id: '/team/Team',
  path: '/team/Team',
  getParentRoute: () => OrgProjectRoute,
} as any)
const OrgProjectSettingsSettingsRoute =
  OrgProjectSettingsSettingsRouteImport.update({
    id: '/settings/Settings',
    path: '/settings/Settings',
    getParentRoute: () => OrgProjectRoute,
  } as any)
const OrgProjectNarrativeAssetsVariablesRoute =
  OrgProjectNarrativeAssetsVariablesRouteImport.update({
    id: '/narrative-assets/Variables',
    path: '/narrative-assets/Variables',
    getParentRoute: () => OrgProjectRoute,
  } as any)
const OrgProjectNarrativeAssetsStoryNodesRoute =
  OrgProjectNarrativeAssetsStoryNodesRouteImport.update({
    id: '/narrative-assets/StoryNodes',
    path: '/narrative-assets/StoryNodes',
    getParentRoute: () => OrgProjectRoute,
  } as any)
const OrgProjectNarrativeAssetsQuestRoute =
  OrgProjectNarrativeAssetsQuestRouteImport.update({
    id: '/narrative-assets/Quest',
    path: '/narrative-assets/Quest',
    getParentRoute: () => OrgProjectRoute,
  } as any)
const OrgProjectNarrativeAssetsLocationsRoute =
  OrgProjectNarrativeAssetsLocationsRouteImport.update({
    id: '/narrative-assets/Locations',
    path: '/narrative-assets/Locations',
    getParentRoute: () => OrgProjectRoute,
  } as any)
const OrgProjectNarrativeAssetsItemsRoute =
  OrgProjectNarrativeAssetsItemsRouteImport.update({
    id: '/narrative-assets/Items',
    path: '/narrative-assets/Items',
    getParentRoute: () => OrgProjectRoute,
  } as any)
const OrgProjectNarrativeAssetsFactionsRoute =
  OrgProjectNarrativeAssetsFactionsRouteImport.update({
    id: '/narrative-assets/Factions',
    path: '/narrative-assets/Factions',
    getParentRoute: () => OrgProjectRoute,
  } as any)
const OrgProjectNarrativeAssetsDialogueRoute =
  OrgProjectNarrativeAssetsDialogueRouteImport.update({
    id: '/narrative-assets/Dialogue',
    path: '/narrative-assets/Dialogue',
    getParentRoute: () => OrgProjectRoute,
  } as any)
const OrgProjectNarrativeAssetsConditionsRoute =
  OrgProjectNarrativeAssetsConditionsRouteImport.update({
    id: '/narrative-assets/Conditions',
    path: '/narrative-assets/Conditions',
    getParentRoute: () => OrgProjectRoute,
  } as any)
const OrgProjectNarrativeAssetsCharactersRoute =
  OrgProjectNarrativeAssetsCharactersRouteImport.update({
    id: '/narrative-assets/Characters',
    path: '/narrative-assets/Characters',
    getParentRoute: () => OrgProjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/org': typeof OrgRouteWithChildren
  '/org/billing': typeof OrgBillingRoute
  '/org/project': typeof OrgProjectRouteWithChildren
  '/org/teams': typeof OrgTeamsRoute
  '/org/': typeof OrgIndexRoute
  '/org/analytics/Analytics': typeof OrgAnalyticsAnalyticsRoute
  '/org/project/Editor': typeof OrgProjectEditorRoute
  '/org/project/SDK': typeof OrgProjectSDKRoute
  '/org/org-setting/': typeof OrgOrgSettingIndexRoute
  '/org/project/': typeof OrgProjectIndexRoute
  '/org/project/narrative-assets/Characters': typeof OrgProjectNarrativeAssetsCharactersRoute
  '/org/project/narrative-assets/Conditions': typeof OrgProjectNarrativeAssetsConditionsRoute
  '/org/project/narrative-assets/Dialogue': typeof OrgProjectNarrativeAssetsDialogueRoute
  '/org/project/narrative-assets/Factions': typeof OrgProjectNarrativeAssetsFactionsRoute
  '/org/project/narrative-assets/Items': typeof OrgProjectNarrativeAssetsItemsRoute
  '/org/project/narrative-assets/Locations': typeof OrgProjectNarrativeAssetsLocationsRoute
  '/org/project/narrative-assets/Quest': typeof OrgProjectNarrativeAssetsQuestRoute
  '/org/project/narrative-assets/StoryNodes': typeof OrgProjectNarrativeAssetsStoryNodesRoute
  '/org/project/narrative-assets/Variables': typeof OrgProjectNarrativeAssetsVariablesRoute
  '/org/project/settings/Settings': typeof OrgProjectSettingsSettingsRoute
  '/org/project/team/Team': typeof OrgProjectTeamTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/org/billing': typeof OrgBillingRoute
  '/org/teams': typeof OrgTeamsRoute
  '/org': typeof OrgIndexRoute
  '/org/analytics/Analytics': typeof OrgAnalyticsAnalyticsRoute
  '/org/project/Editor': typeof OrgProjectEditorRoute
  '/org/project/SDK': typeof OrgProjectSDKRoute
  '/org/org-setting': typeof OrgOrgSettingIndexRoute
  '/org/project': typeof OrgProjectIndexRoute
  '/org/project/narrative-assets/Characters': typeof OrgProjectNarrativeAssetsCharactersRoute
  '/org/project/narrative-assets/Conditions': typeof OrgProjectNarrativeAssetsConditionsRoute
  '/org/project/narrative-assets/Dialogue': typeof OrgProjectNarrativeAssetsDialogueRoute
  '/org/project/narrative-assets/Factions': typeof OrgProjectNarrativeAssetsFactionsRoute
  '/org/project/narrative-assets/Items': typeof OrgProjectNarrativeAssetsItemsRoute
  '/org/project/narrative-assets/Locations': typeof OrgProjectNarrativeAssetsLocationsRoute
  '/org/project/narrative-assets/Quest': typeof OrgProjectNarrativeAssetsQuestRoute
  '/org/project/narrative-assets/StoryNodes': typeof OrgProjectNarrativeAssetsStoryNodesRoute
  '/org/project/narrative-assets/Variables': typeof OrgProjectNarrativeAssetsVariablesRoute
  '/org/project/settings/Settings': typeof OrgProjectSettingsSettingsRoute
  '/org/project/team/Team': typeof OrgProjectTeamTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/org': typeof OrgRouteWithChildren
  '/org/billing': typeof OrgBillingRoute
  '/org/project': typeof OrgProjectRouteWithChildren
  '/org/teams': typeof OrgTeamsRoute
  '/org/': typeof OrgIndexRoute
  '/org/analytics/Analytics': typeof OrgAnalyticsAnalyticsRoute
  '/org/project/Editor': typeof OrgProjectEditorRoute
  '/org/project/SDK': typeof OrgProjectSDKRoute
  '/org/org-setting/': typeof OrgOrgSettingIndexRoute
  '/org/project/': typeof OrgProjectIndexRoute
  '/org/project/narrative-assets/Characters': typeof OrgProjectNarrativeAssetsCharactersRoute
  '/org/project/narrative-assets/Conditions': typeof OrgProjectNarrativeAssetsConditionsRoute
  '/org/project/narrative-assets/Dialogue': typeof OrgProjectNarrativeAssetsDialogueRoute
  '/org/project/narrative-assets/Factions': typeof OrgProjectNarrativeAssetsFactionsRoute
  '/org/project/narrative-assets/Items': typeof OrgProjectNarrativeAssetsItemsRoute
  '/org/project/narrative-assets/Locations': typeof OrgProjectNarrativeAssetsLocationsRoute
  '/org/project/narrative-assets/Quest': typeof OrgProjectNarrativeAssetsQuestRoute
  '/org/project/narrative-assets/StoryNodes': typeof OrgProjectNarrativeAssetsStoryNodesRoute
  '/org/project/narrative-assets/Variables': typeof OrgProjectNarrativeAssetsVariablesRoute
  '/org/project/settings/Settings': typeof OrgProjectSettingsSettingsRoute
  '/org/project/team/Team': typeof OrgProjectTeamTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/org'
    | '/org/billing'
    | '/org/project'
    | '/org/teams'
    | '/org/'
    | '/org/analytics/Analytics'
    | '/org/project/Editor'
    | '/org/project/SDK'
    | '/org/org-setting/'
    | '/org/project/'
    | '/org/project/narrative-assets/Characters'
    | '/org/project/narrative-assets/Conditions'
    | '/org/project/narrative-assets/Dialogue'
    | '/org/project/narrative-assets/Factions'
    | '/org/project/narrative-assets/Items'
    | '/org/project/narrative-assets/Locations'
    | '/org/project/narrative-assets/Quest'
    | '/org/project/narrative-assets/StoryNodes'
    | '/org/project/narrative-assets/Variables'
    | '/org/project/settings/Settings'
    | '/org/project/team/Team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/org/billing'
    | '/org/teams'
    | '/org'
    | '/org/analytics/Analytics'
    | '/org/project/Editor'
    | '/org/project/SDK'
    | '/org/org-setting'
    | '/org/project'
    | '/org/project/narrative-assets/Characters'
    | '/org/project/narrative-assets/Conditions'
    | '/org/project/narrative-assets/Dialogue'
    | '/org/project/narrative-assets/Factions'
    | '/org/project/narrative-assets/Items'
    | '/org/project/narrative-assets/Locations'
    | '/org/project/narrative-assets/Quest'
    | '/org/project/narrative-assets/StoryNodes'
    | '/org/project/narrative-assets/Variables'
    | '/org/project/settings/Settings'
    | '/org/project/team/Team'
  id:
    | '__root__'
    | '/'
    | '/org'
    | '/org/billing'
    | '/org/project'
    | '/org/teams'
    | '/org/'
    | '/org/analytics/Analytics'
    | '/org/project/Editor'
    | '/org/project/SDK'
    | '/org/org-setting/'
    | '/org/project/'
    | '/org/project/narrative-assets/Characters'
    | '/org/project/narrative-assets/Conditions'
    | '/org/project/narrative-assets/Dialogue'
    | '/org/project/narrative-assets/Factions'
    | '/org/project/narrative-assets/Items'
    | '/org/project/narrative-assets/Locations'
    | '/org/project/narrative-assets/Quest'
    | '/org/project/narrative-assets/StoryNodes'
    | '/org/project/narrative-assets/Variables'
    | '/org/project/settings/Settings'
    | '/org/project/team/Team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgRoute: typeof OrgRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/teams': {
      id: '/org/teams'
      path: '/teams'
      fullPath: '/org/teams'
      preLoaderRoute: typeof OrgTeamsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/project': {
      id: '/org/project'
      path: '/project'
      fullPath: '/org/project'
      preLoaderRoute: typeof OrgProjectRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/billing': {
      id: '/org/billing'
      path: '/billing'
      fullPath: '/org/billing'
      preLoaderRoute: typeof OrgBillingRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/project/': {
      id: '/org/project/'
      path: '/'
      fullPath: '/org/project/'
      preLoaderRoute: typeof OrgProjectIndexRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/org-setting/': {
      id: '/org/org-setting/'
      path: '/org-setting'
      fullPath: '/org/org-setting/'
      preLoaderRoute: typeof OrgOrgSettingIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/project/SDK': {
      id: '/org/project/SDK'
      path: '/SDK'
      fullPath: '/org/project/SDK'
      preLoaderRoute: typeof OrgProjectSDKRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/Editor': {
      id: '/org/project/Editor'
      path: '/Editor'
      fullPath: '/org/project/Editor'
      preLoaderRoute: typeof OrgProjectEditorRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/analytics/Analytics': {
      id: '/org/analytics/Analytics'
      path: '/analytics/Analytics'
      fullPath: '/org/analytics/Analytics'
      preLoaderRoute: typeof OrgAnalyticsAnalyticsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/project/team/Team': {
      id: '/org/project/team/Team'
      path: '/team/Team'
      fullPath: '/org/project/team/Team'
      preLoaderRoute: typeof OrgProjectTeamTeamRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/settings/Settings': {
      id: '/org/project/settings/Settings'
      path: '/settings/Settings'
      fullPath: '/org/project/settings/Settings'
      preLoaderRoute: typeof OrgProjectSettingsSettingsRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/narrative-assets/Variables': {
      id: '/org/project/narrative-assets/Variables'
      path: '/narrative-assets/Variables'
      fullPath: '/org/project/narrative-assets/Variables'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsVariablesRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/narrative-assets/StoryNodes': {
      id: '/org/project/narrative-assets/StoryNodes'
      path: '/narrative-assets/StoryNodes'
      fullPath: '/org/project/narrative-assets/StoryNodes'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsStoryNodesRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/narrative-assets/Quest': {
      id: '/org/project/narrative-assets/Quest'
      path: '/narrative-assets/Quest'
      fullPath: '/org/project/narrative-assets/Quest'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsQuestRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/narrative-assets/Locations': {
      id: '/org/project/narrative-assets/Locations'
      path: '/narrative-assets/Locations'
      fullPath: '/org/project/narrative-assets/Locations'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsLocationsRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/narrative-assets/Items': {
      id: '/org/project/narrative-assets/Items'
      path: '/narrative-assets/Items'
      fullPath: '/org/project/narrative-assets/Items'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsItemsRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/narrative-assets/Factions': {
      id: '/org/project/narrative-assets/Factions'
      path: '/narrative-assets/Factions'
      fullPath: '/org/project/narrative-assets/Factions'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsFactionsRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/narrative-assets/Dialogue': {
      id: '/org/project/narrative-assets/Dialogue'
      path: '/narrative-assets/Dialogue'
      fullPath: '/org/project/narrative-assets/Dialogue'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsDialogueRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/narrative-assets/Conditions': {
      id: '/org/project/narrative-assets/Conditions'
      path: '/narrative-assets/Conditions'
      fullPath: '/org/project/narrative-assets/Conditions'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsConditionsRouteImport
      parentRoute: typeof OrgProjectRoute
    }
    '/org/project/narrative-assets/Characters': {
      id: '/org/project/narrative-assets/Characters'
      path: '/narrative-assets/Characters'
      fullPath: '/org/project/narrative-assets/Characters'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsCharactersRouteImport
      parentRoute: typeof OrgProjectRoute
    }
  }
}

interface OrgProjectRouteChildren {
  OrgProjectEditorRoute: typeof OrgProjectEditorRoute
  OrgProjectSDKRoute: typeof OrgProjectSDKRoute
  OrgProjectIndexRoute: typeof OrgProjectIndexRoute
  OrgProjectNarrativeAssetsCharactersRoute: typeof OrgProjectNarrativeAssetsCharactersRoute
  OrgProjectNarrativeAssetsConditionsRoute: typeof OrgProjectNarrativeAssetsConditionsRoute
  OrgProjectNarrativeAssetsDialogueRoute: typeof OrgProjectNarrativeAssetsDialogueRoute
  OrgProjectNarrativeAssetsFactionsRoute: typeof OrgProjectNarrativeAssetsFactionsRoute
  OrgProjectNarrativeAssetsItemsRoute: typeof OrgProjectNarrativeAssetsItemsRoute
  OrgProjectNarrativeAssetsLocationsRoute: typeof OrgProjectNarrativeAssetsLocationsRoute
  OrgProjectNarrativeAssetsQuestRoute: typeof OrgProjectNarrativeAssetsQuestRoute
  OrgProjectNarrativeAssetsStoryNodesRoute: typeof OrgProjectNarrativeAssetsStoryNodesRoute
  OrgProjectNarrativeAssetsVariablesRoute: typeof OrgProjectNarrativeAssetsVariablesRoute
  OrgProjectSettingsSettingsRoute: typeof OrgProjectSettingsSettingsRoute
  OrgProjectTeamTeamRoute: typeof OrgProjectTeamTeamRoute
}

const OrgProjectRouteChildren: OrgProjectRouteChildren = {
  OrgProjectEditorRoute: OrgProjectEditorRoute,
  OrgProjectSDKRoute: OrgProjectSDKRoute,
  OrgProjectIndexRoute: OrgProjectIndexRoute,
  OrgProjectNarrativeAssetsCharactersRoute:
    OrgProjectNarrativeAssetsCharactersRoute,
  OrgProjectNarrativeAssetsConditionsRoute:
    OrgProjectNarrativeAssetsConditionsRoute,
  OrgProjectNarrativeAssetsDialogueRoute:
    OrgProjectNarrativeAssetsDialogueRoute,
  OrgProjectNarrativeAssetsFactionsRoute:
    OrgProjectNarrativeAssetsFactionsRoute,
  OrgProjectNarrativeAssetsItemsRoute: OrgProjectNarrativeAssetsItemsRoute,
  OrgProjectNarrativeAssetsLocationsRoute:
    OrgProjectNarrativeAssetsLocationsRoute,
  OrgProjectNarrativeAssetsQuestRoute: OrgProjectNarrativeAssetsQuestRoute,
  OrgProjectNarrativeAssetsStoryNodesRoute:
    OrgProjectNarrativeAssetsStoryNodesRoute,
  OrgProjectNarrativeAssetsVariablesRoute:
    OrgProjectNarrativeAssetsVariablesRoute,
  OrgProjectSettingsSettingsRoute: OrgProjectSettingsSettingsRoute,
  OrgProjectTeamTeamRoute: OrgProjectTeamTeamRoute,
}

const OrgProjectRouteWithChildren = OrgProjectRoute._addFileChildren(
  OrgProjectRouteChildren,
)

interface OrgRouteChildren {
  OrgBillingRoute: typeof OrgBillingRoute
  OrgProjectRoute: typeof OrgProjectRouteWithChildren
  OrgTeamsRoute: typeof OrgTeamsRoute
  OrgIndexRoute: typeof OrgIndexRoute
  OrgAnalyticsAnalyticsRoute: typeof OrgAnalyticsAnalyticsRoute
  OrgOrgSettingIndexRoute: typeof OrgOrgSettingIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgBillingRoute: OrgBillingRoute,
  OrgProjectRoute: OrgProjectRouteWithChildren,
  OrgTeamsRoute: OrgTeamsRoute,
  OrgIndexRoute: OrgIndexRoute,
  OrgAnalyticsAnalyticsRoute: OrgAnalyticsAnalyticsRoute,
  OrgOrgSettingIndexRoute: OrgOrgSettingIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgRoute: OrgRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
