/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/org/index'
import { Route as OrgTeamsRouteImport } from './routes/org/teams'
import { Route as OrgBillingRouteImport } from './routes/org/billing'
import { Route as OrgProjectIndexRouteImport } from './routes/org/project/index'
import { Route as OrgOrgSettingIndexRouteImport } from './routes/org/org-setting/index'
import { Route as OrgProjectSDKRouteImport } from './routes/org/project/SDK'
import { Route as OrgProjectEditorRouteImport } from './routes/org/project/Editor'
import { Route as OrgAnalyticsAnalyticsRouteImport } from './routes/org/analytics/Analytics'
import { Route as OrgProjectTeamTeamRouteImport } from './routes/org/project/team/Team'
import { Route as OrgProjectSettingsSettingsRouteImport } from './routes/org/project/settings/Settings'
import { Route as OrgProjectNarrativeAssetsVariablesRouteImport } from './routes/org/project/narrative-assets/Variables'
import { Route as OrgProjectNarrativeAssetsQuestRouteImport } from './routes/org/project/narrative-assets/Quest'
import { Route as OrgProjectNarrativeAssetsLocationsRouteImport } from './routes/org/project/narrative-assets/Locations'
import { Route as OrgProjectNarrativeAssetsDialogueRouteImport } from './routes/org/project/narrative-assets/Dialogue'
import { Route as OrgProjectNarrativeAssetsCharactersRouteImport } from './routes/org/project/narrative-assets/Characters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamsRoute = OrgTeamsRouteImport.update({
  id: '/org/teams',
  path: '/org/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgBillingRoute = OrgBillingRouteImport.update({
  id: '/org/billing',
  path: '/org/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgProjectIndexRoute = OrgProjectIndexRouteImport.update({
  id: '/org/project/',
  path: '/org/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgSettingIndexRoute = OrgOrgSettingIndexRouteImport.update({
  id: '/org/org-setting/',
  path: '/org/org-setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgProjectSDKRoute = OrgProjectSDKRouteImport.update({
  id: '/org/project/SDK',
  path: '/org/project/SDK',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgProjectEditorRoute = OrgProjectEditorRouteImport.update({
  id: '/org/project/Editor',
  path: '/org/project/Editor',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgAnalyticsAnalyticsRoute = OrgAnalyticsAnalyticsRouteImport.update({
  id: '/org/analytics/Analytics',
  path: '/org/analytics/Analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgProjectTeamTeamRoute = OrgProjectTeamTeamRouteImport.update({
  id: '/org/project/team/Team',
  path: '/org/project/team/Team',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgProjectSettingsSettingsRoute =
  OrgProjectSettingsSettingsRouteImport.update({
    id: '/org/project/settings/Settings',
    path: '/org/project/settings/Settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgProjectNarrativeAssetsVariablesRoute =
  OrgProjectNarrativeAssetsVariablesRouteImport.update({
    id: '/org/project/narrative-assets/Variables',
    path: '/org/project/narrative-assets/Variables',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgProjectNarrativeAssetsQuestRoute =
  OrgProjectNarrativeAssetsQuestRouteImport.update({
    id: '/org/project/narrative-assets/Quest',
    path: '/org/project/narrative-assets/Quest',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgProjectNarrativeAssetsLocationsRoute =
  OrgProjectNarrativeAssetsLocationsRouteImport.update({
    id: '/org/project/narrative-assets/Locations',
    path: '/org/project/narrative-assets/Locations',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgProjectNarrativeAssetsDialogueRoute =
  OrgProjectNarrativeAssetsDialogueRouteImport.update({
    id: '/org/project/narrative-assets/Dialogue',
    path: '/org/project/narrative-assets/Dialogue',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgProjectNarrativeAssetsCharactersRoute =
  OrgProjectNarrativeAssetsCharactersRouteImport.update({
    id: '/org/project/narrative-assets/Characters',
    path: '/org/project/narrative-assets/Characters',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/org/billing': typeof OrgBillingRoute
  '/org/teams': typeof OrgTeamsRoute
  '/org/': typeof OrgIndexRoute
  '/org/analytics/Analytics': typeof OrgAnalyticsAnalyticsRoute
  '/org/project/Editor': typeof OrgProjectEditorRoute
  '/org/project/SDK': typeof OrgProjectSDKRoute
  '/org/org-setting/': typeof OrgOrgSettingIndexRoute
  '/org/project/': typeof OrgProjectIndexRoute
  '/org/project/narrative-assets/Characters': typeof OrgProjectNarrativeAssetsCharactersRoute
  '/org/project/narrative-assets/Dialogue': typeof OrgProjectNarrativeAssetsDialogueRoute
  '/org/project/narrative-assets/Locations': typeof OrgProjectNarrativeAssetsLocationsRoute
  '/org/project/narrative-assets/Quest': typeof OrgProjectNarrativeAssetsQuestRoute
  '/org/project/narrative-assets/Variables': typeof OrgProjectNarrativeAssetsVariablesRoute
  '/org/project/settings/Settings': typeof OrgProjectSettingsSettingsRoute
  '/org/project/team/Team': typeof OrgProjectTeamTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/org/billing': typeof OrgBillingRoute
  '/org/teams': typeof OrgTeamsRoute
  '/org': typeof OrgIndexRoute
  '/org/analytics/Analytics': typeof OrgAnalyticsAnalyticsRoute
  '/org/project/Editor': typeof OrgProjectEditorRoute
  '/org/project/SDK': typeof OrgProjectSDKRoute
  '/org/org-setting': typeof OrgOrgSettingIndexRoute
  '/org/project': typeof OrgProjectIndexRoute
  '/org/project/narrative-assets/Characters': typeof OrgProjectNarrativeAssetsCharactersRoute
  '/org/project/narrative-assets/Dialogue': typeof OrgProjectNarrativeAssetsDialogueRoute
  '/org/project/narrative-assets/Locations': typeof OrgProjectNarrativeAssetsLocationsRoute
  '/org/project/narrative-assets/Quest': typeof OrgProjectNarrativeAssetsQuestRoute
  '/org/project/narrative-assets/Variables': typeof OrgProjectNarrativeAssetsVariablesRoute
  '/org/project/settings/Settings': typeof OrgProjectSettingsSettingsRoute
  '/org/project/team/Team': typeof OrgProjectTeamTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/org/billing': typeof OrgBillingRoute
  '/org/teams': typeof OrgTeamsRoute
  '/org/': typeof OrgIndexRoute
  '/org/analytics/Analytics': typeof OrgAnalyticsAnalyticsRoute
  '/org/project/Editor': typeof OrgProjectEditorRoute
  '/org/project/SDK': typeof OrgProjectSDKRoute
  '/org/org-setting/': typeof OrgOrgSettingIndexRoute
  '/org/project/': typeof OrgProjectIndexRoute
  '/org/project/narrative-assets/Characters': typeof OrgProjectNarrativeAssetsCharactersRoute
  '/org/project/narrative-assets/Dialogue': typeof OrgProjectNarrativeAssetsDialogueRoute
  '/org/project/narrative-assets/Locations': typeof OrgProjectNarrativeAssetsLocationsRoute
  '/org/project/narrative-assets/Quest': typeof OrgProjectNarrativeAssetsQuestRoute
  '/org/project/narrative-assets/Variables': typeof OrgProjectNarrativeAssetsVariablesRoute
  '/org/project/settings/Settings': typeof OrgProjectSettingsSettingsRoute
  '/org/project/team/Team': typeof OrgProjectTeamTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/org/billing'
    | '/org/teams'
    | '/org/'
    | '/org/analytics/Analytics'
    | '/org/project/Editor'
    | '/org/project/SDK'
    | '/org/org-setting/'
    | '/org/project/'
    | '/org/project/narrative-assets/Characters'
    | '/org/project/narrative-assets/Dialogue'
    | '/org/project/narrative-assets/Locations'
    | '/org/project/narrative-assets/Quest'
    | '/org/project/narrative-assets/Variables'
    | '/org/project/settings/Settings'
    | '/org/project/team/Team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/org/billing'
    | '/org/teams'
    | '/org'
    | '/org/analytics/Analytics'
    | '/org/project/Editor'
    | '/org/project/SDK'
    | '/org/org-setting'
    | '/org/project'
    | '/org/project/narrative-assets/Characters'
    | '/org/project/narrative-assets/Dialogue'
    | '/org/project/narrative-assets/Locations'
    | '/org/project/narrative-assets/Quest'
    | '/org/project/narrative-assets/Variables'
    | '/org/project/settings/Settings'
    | '/org/project/team/Team'
  id:
    | '__root__'
    | '/'
    | '/org/billing'
    | '/org/teams'
    | '/org/'
    | '/org/analytics/Analytics'
    | '/org/project/Editor'
    | '/org/project/SDK'
    | '/org/org-setting/'
    | '/org/project/'
    | '/org/project/narrative-assets/Characters'
    | '/org/project/narrative-assets/Dialogue'
    | '/org/project/narrative-assets/Locations'
    | '/org/project/narrative-assets/Quest'
    | '/org/project/narrative-assets/Variables'
    | '/org/project/settings/Settings'
    | '/org/project/team/Team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgBillingRoute: typeof OrgBillingRoute
  OrgTeamsRoute: typeof OrgTeamsRoute
  OrgIndexRoute: typeof OrgIndexRoute
  OrgAnalyticsAnalyticsRoute: typeof OrgAnalyticsAnalyticsRoute
  OrgProjectEditorRoute: typeof OrgProjectEditorRoute
  OrgProjectSDKRoute: typeof OrgProjectSDKRoute
  OrgOrgSettingIndexRoute: typeof OrgOrgSettingIndexRoute
  OrgProjectIndexRoute: typeof OrgProjectIndexRoute
  OrgProjectNarrativeAssetsCharactersRoute: typeof OrgProjectNarrativeAssetsCharactersRoute
  OrgProjectNarrativeAssetsDialogueRoute: typeof OrgProjectNarrativeAssetsDialogueRoute
  OrgProjectNarrativeAssetsLocationsRoute: typeof OrgProjectNarrativeAssetsLocationsRoute
  OrgProjectNarrativeAssetsQuestRoute: typeof OrgProjectNarrativeAssetsQuestRoute
  OrgProjectNarrativeAssetsVariablesRoute: typeof OrgProjectNarrativeAssetsVariablesRoute
  OrgProjectSettingsSettingsRoute: typeof OrgProjectSettingsSettingsRoute
  OrgProjectTeamTeamRoute: typeof OrgProjectTeamTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/org'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/teams': {
      id: '/org/teams'
      path: '/org/teams'
      fullPath: '/org/teams'
      preLoaderRoute: typeof OrgTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/billing': {
      id: '/org/billing'
      path: '/org/billing'
      fullPath: '/org/billing'
      preLoaderRoute: typeof OrgBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/': {
      id: '/org/project/'
      path: '/org/project'
      fullPath: '/org/project/'
      preLoaderRoute: typeof OrgProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/org-setting/': {
      id: '/org/org-setting/'
      path: '/org/org-setting'
      fullPath: '/org/org-setting/'
      preLoaderRoute: typeof OrgOrgSettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/SDK': {
      id: '/org/project/SDK'
      path: '/org/project/SDK'
      fullPath: '/org/project/SDK'
      preLoaderRoute: typeof OrgProjectSDKRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/Editor': {
      id: '/org/project/Editor'
      path: '/org/project/Editor'
      fullPath: '/org/project/Editor'
      preLoaderRoute: typeof OrgProjectEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/analytics/Analytics': {
      id: '/org/analytics/Analytics'
      path: '/org/analytics/Analytics'
      fullPath: '/org/analytics/Analytics'
      preLoaderRoute: typeof OrgAnalyticsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/team/Team': {
      id: '/org/project/team/Team'
      path: '/org/project/team/Team'
      fullPath: '/org/project/team/Team'
      preLoaderRoute: typeof OrgProjectTeamTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/settings/Settings': {
      id: '/org/project/settings/Settings'
      path: '/org/project/settings/Settings'
      fullPath: '/org/project/settings/Settings'
      preLoaderRoute: typeof OrgProjectSettingsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/narrative-assets/Variables': {
      id: '/org/project/narrative-assets/Variables'
      path: '/org/project/narrative-assets/Variables'
      fullPath: '/org/project/narrative-assets/Variables'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsVariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/narrative-assets/Quest': {
      id: '/org/project/narrative-assets/Quest'
      path: '/org/project/narrative-assets/Quest'
      fullPath: '/org/project/narrative-assets/Quest'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsQuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/narrative-assets/Locations': {
      id: '/org/project/narrative-assets/Locations'
      path: '/org/project/narrative-assets/Locations'
      fullPath: '/org/project/narrative-assets/Locations'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/narrative-assets/Dialogue': {
      id: '/org/project/narrative-assets/Dialogue'
      path: '/org/project/narrative-assets/Dialogue'
      fullPath: '/org/project/narrative-assets/Dialogue'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsDialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/narrative-assets/Characters': {
      id: '/org/project/narrative-assets/Characters'
      path: '/org/project/narrative-assets/Characters'
      fullPath: '/org/project/narrative-assets/Characters'
      preLoaderRoute: typeof OrgProjectNarrativeAssetsCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgBillingRoute: OrgBillingRoute,
  OrgTeamsRoute: OrgTeamsRoute,
  OrgIndexRoute: OrgIndexRoute,
  OrgAnalyticsAnalyticsRoute: OrgAnalyticsAnalyticsRoute,
  OrgProjectEditorRoute: OrgProjectEditorRoute,
  OrgProjectSDKRoute: OrgProjectSDKRoute,
  OrgOrgSettingIndexRoute: OrgOrgSettingIndexRoute,
  OrgProjectIndexRoute: OrgProjectIndexRoute,
  OrgProjectNarrativeAssetsCharactersRoute:
    OrgProjectNarrativeAssetsCharactersRoute,
  OrgProjectNarrativeAssetsDialogueRoute:
    OrgProjectNarrativeAssetsDialogueRoute,
  OrgProjectNarrativeAssetsLocationsRoute:
    OrgProjectNarrativeAssetsLocationsRoute,
  OrgProjectNarrativeAssetsQuestRoute: OrgProjectNarrativeAssetsQuestRoute,
  OrgProjectNarrativeAssetsVariablesRoute:
    OrgProjectNarrativeAssetsVariablesRoute,
  OrgProjectSettingsSettingsRoute: OrgProjectSettingsSettingsRoute,
  OrgProjectTeamTeamRoute: OrgProjectTeamTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
