/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/org/index'
import { Route as OrgTeamsRouteImport } from './routes/org/teams'
import { Route as OrgBillingRouteImport } from './routes/org/billing'
import { Route as OrgProjectIndexRouteImport } from './routes/org/project/index'
import { Route as OrgProjectSdkIndexRouteImport } from './routes/org/project/sdk/index'
import { Route as OrgProjectEditorIndexRouteImport } from './routes/org/project/editor/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamsRoute = OrgTeamsRouteImport.update({
  id: '/org/teams',
  path: '/org/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgBillingRoute = OrgBillingRouteImport.update({
  id: '/org/billing',
  path: '/org/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgProjectIndexRoute = OrgProjectIndexRouteImport.update({
  id: '/org/project/',
  path: '/org/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgProjectSdkIndexRoute = OrgProjectSdkIndexRouteImport.update({
  id: '/org/project/sdk/',
  path: '/org/project/sdk/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgProjectEditorIndexRoute = OrgProjectEditorIndexRouteImport.update({
  id: '/org/project/editor/',
  path: '/org/project/editor/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/org/billing': typeof OrgBillingRoute
  '/org/teams': typeof OrgTeamsRoute
  '/org/': typeof OrgIndexRoute
  '/org/project/': typeof OrgProjectIndexRoute
  '/org/project/editor/': typeof OrgProjectEditorIndexRoute
  '/org/project/sdk/': typeof OrgProjectSdkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/org/billing': typeof OrgBillingRoute
  '/org/teams': typeof OrgTeamsRoute
  '/org': typeof OrgIndexRoute
  '/org/project': typeof OrgProjectIndexRoute
  '/org/project/editor': typeof OrgProjectEditorIndexRoute
  '/org/project/sdk': typeof OrgProjectSdkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/org/billing': typeof OrgBillingRoute
  '/org/teams': typeof OrgTeamsRoute
  '/org/': typeof OrgIndexRoute
  '/org/project/': typeof OrgProjectIndexRoute
  '/org/project/editor/': typeof OrgProjectEditorIndexRoute
  '/org/project/sdk/': typeof OrgProjectSdkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/org/billing'
    | '/org/teams'
    | '/org/'
    | '/org/project/'
    | '/org/project/editor/'
    | '/org/project/sdk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/org/billing'
    | '/org/teams'
    | '/org'
    | '/org/project'
    | '/org/project/editor'
    | '/org/project/sdk'
  id:
    | '__root__'
    | '/'
    | '/org/billing'
    | '/org/teams'
    | '/org/'
    | '/org/project/'
    | '/org/project/editor/'
    | '/org/project/sdk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgBillingRoute: typeof OrgBillingRoute
  OrgTeamsRoute: typeof OrgTeamsRoute
  OrgIndexRoute: typeof OrgIndexRoute
  OrgProjectIndexRoute: typeof OrgProjectIndexRoute
  OrgProjectEditorIndexRoute: typeof OrgProjectEditorIndexRoute
  OrgProjectSdkIndexRoute: typeof OrgProjectSdkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/org'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/teams': {
      id: '/org/teams'
      path: '/org/teams'
      fullPath: '/org/teams'
      preLoaderRoute: typeof OrgTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/billing': {
      id: '/org/billing'
      path: '/org/billing'
      fullPath: '/org/billing'
      preLoaderRoute: typeof OrgBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/': {
      id: '/org/project/'
      path: '/org/project'
      fullPath: '/org/project/'
      preLoaderRoute: typeof OrgProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/sdk/': {
      id: '/org/project/sdk/'
      path: '/org/project/sdk'
      fullPath: '/org/project/sdk/'
      preLoaderRoute: typeof OrgProjectSdkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/project/editor/': {
      id: '/org/project/editor/'
      path: '/org/project/editor'
      fullPath: '/org/project/editor/'
      preLoaderRoute: typeof OrgProjectEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgBillingRoute: OrgBillingRoute,
  OrgTeamsRoute: OrgTeamsRoute,
  OrgIndexRoute: OrgIndexRoute,
  OrgProjectIndexRoute: OrgProjectIndexRoute,
  OrgProjectEditorIndexRoute: OrgProjectEditorIndexRoute,
  OrgProjectSdkIndexRoute: OrgProjectSdkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
